service:
  name: service-grafana
  namespace: aicares
image:
  repository: grafana/grafana
  tag: "13.0.1"
containerPort: 3000
resources:
  limits:
    memory: "200Mi"
  requests:
    memory: "64Mi"
    cpu: "50m"
env: []
nodeSelector:
  eks.amazonaws.com/nodegroup: graviton-workers
